// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file greeter/v1/greeter.proto (package greeter.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file greeter/v1/greeter.proto.
 */
export const file_greeter_v1_greeter: GenFile = /*@__PURE__*/
  fileDesc("ChhncmVldGVyL3YxL2dyZWV0ZXIucHJvdG8SCmdyZWV0ZXIudjEiHwoPU2F5SGVsbG9SZXF1ZXN0EgwKBG5hbWUYASABKAkiIwoQU2F5SGVsbG9SZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJIicKFFN0cmVhbWluZ0VjaG9SZXF1ZXN0Eg8KB21lc3NhZ2UYASABKAkiKAoVU3RyZWFtaW5nRWNob1Jlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkiKAoYQmlkaVN0cmVhbWluZ0VjaG9SZXF1ZXN0EgwKBG5hbWUYASABKAkiLQoZQmlkaVN0cmVhbWluZ0VjaG9SZXNwb25zZRIQCghncmVldGluZxgBIAEoCTKbAgoOR3JlZXRlclNlcnZpY2USRwoIU2F5SGVsbG8SGy5ncmVldGVyLnYxLlNheUhlbGxvUmVxdWVzdBocLmdyZWV0ZXIudjEuU2F5SGVsbG9SZXNwb25zZSIAElgKDVN0cmVhbWluZ0VjaG8SIC5ncmVldGVyLnYxLlN0cmVhbWluZ0VjaG9SZXF1ZXN0GiEuZ3JlZXRlci52MS5TdHJlYW1pbmdFY2hvUmVzcG9uc2UiADABEmYKEUJpZGlTdHJlYW1pbmdFY2hvEiQuZ3JlZXRlci52MS5CaWRpU3RyZWFtaW5nRWNob1JlcXVlc3QaJS5ncmVldGVyLnYxLkJpZGlTdHJlYW1pbmdFY2hvUmVzcG9uc2UiACgBMAFCqgEKDmNvbS5ncmVldGVyLnYxQgxHcmVldGVyUHJvdG9QAVpBZ2l0aHViLmNvbS9vbWdvbGFiL2RycGMvZXhhbXBsZXMvZWNoby9nZW4vZ28vZ3JlZXRlci92MTtncmVldGVydjGiAgNHWFiqAgpHcmVldGVyLlYxygIKR3JlZXRlclxWMeICFkdyZWV0ZXJcVjFcR1BCTWV0YWRhdGHqAgtHcmVldGVyOjpWMWIGcHJvdG8z");

/**
 * @generated from message greeter.v1.SayHelloRequest
 */
export type SayHelloRequest = Message<"greeter.v1.SayHelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message greeter.v1.SayHelloRequest.
 * Use `create(SayHelloRequestSchema)` to create a new message.
 */
export const SayHelloRequestSchema: GenMessage<SayHelloRequest> = /*@__PURE__*/
  messageDesc(file_greeter_v1_greeter, 0);

/**
 * @generated from message greeter.v1.SayHelloResponse
 */
export type SayHelloResponse = Message<"greeter.v1.SayHelloResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message greeter.v1.SayHelloResponse.
 * Use `create(SayHelloResponseSchema)` to create a new message.
 */
export const SayHelloResponseSchema: GenMessage<SayHelloResponse> = /*@__PURE__*/
  messageDesc(file_greeter_v1_greeter, 1);

/**
 * @generated from message greeter.v1.StreamingEchoRequest
 */
export type StreamingEchoRequest = Message<"greeter.v1.StreamingEchoRequest"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message greeter.v1.StreamingEchoRequest.
 * Use `create(StreamingEchoRequestSchema)` to create a new message.
 */
export const StreamingEchoRequestSchema: GenMessage<StreamingEchoRequest> = /*@__PURE__*/
  messageDesc(file_greeter_v1_greeter, 2);

/**
 * @generated from message greeter.v1.StreamingEchoResponse
 */
export type StreamingEchoResponse = Message<"greeter.v1.StreamingEchoResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message greeter.v1.StreamingEchoResponse.
 * Use `create(StreamingEchoResponseSchema)` to create a new message.
 */
export const StreamingEchoResponseSchema: GenMessage<StreamingEchoResponse> = /*@__PURE__*/
  messageDesc(file_greeter_v1_greeter, 3);

/**
 * @generated from message greeter.v1.BidiStreamingEchoRequest
 */
export type BidiStreamingEchoRequest = Message<"greeter.v1.BidiStreamingEchoRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message greeter.v1.BidiStreamingEchoRequest.
 * Use `create(BidiStreamingEchoRequestSchema)` to create a new message.
 */
export const BidiStreamingEchoRequestSchema: GenMessage<BidiStreamingEchoRequest> = /*@__PURE__*/
  messageDesc(file_greeter_v1_greeter, 4);

/**
 * @generated from message greeter.v1.BidiStreamingEchoResponse
 */
export type BidiStreamingEchoResponse = Message<"greeter.v1.BidiStreamingEchoResponse"> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string;
};

/**
 * Describes the message greeter.v1.BidiStreamingEchoResponse.
 * Use `create(BidiStreamingEchoResponseSchema)` to create a new message.
 */
export const BidiStreamingEchoResponseSchema: GenMessage<BidiStreamingEchoResponse> = /*@__PURE__*/
  messageDesc(file_greeter_v1_greeter, 5);

/**
 * @generated from service greeter.v1.GreeterService
 */
export const GreeterService: GenService<{
  /**
   * @generated from rpc greeter.v1.GreeterService.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof SayHelloRequestSchema;
    output: typeof SayHelloResponseSchema;
  },
  /**
   * @generated from rpc greeter.v1.GreeterService.StreamingEcho
   */
  streamingEcho: {
    methodKind: "server_streaming";
    input: typeof StreamingEchoRequestSchema;
    output: typeof StreamingEchoResponseSchema;
  },
  /**
   * @generated from rpc greeter.v1.GreeterService.BidiStreamingEcho
   */
  bidiStreamingEcho: {
    methodKind: "bidi_streaming";
    input: typeof BidiStreamingEchoRequestSchema;
    output: typeof BidiStreamingEchoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_greeter_v1_greeter, 0);

