// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file greeter/v1/greeter.proto (package greeter.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BidiStreamingEchoRequest, BidiStreamingEchoResponse, SayHelloRequest, SayHelloResponse, StreamingEchoRequest, StreamingEchoResponse } from "./greeter_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service greeter.v1.GreeterService
 */
export const GreeterService = {
  typeName: "greeter.v1.GreeterService",
  methods: {
    /**
     * @generated from rpc greeter.v1.GreeterService.SayHello
     */
    sayHello: {
      name: "SayHello",
      I: SayHelloRequest,
      O: SayHelloResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc greeter.v1.GreeterService.StreamingEcho
     */
    streamingEcho: {
      name: "StreamingEcho",
      I: StreamingEchoRequest,
      O: StreamingEchoResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc greeter.v1.GreeterService.BidiStreamingEcho
     */
    bidiStreamingEcho: {
      name: "BidiStreamingEcho",
      I: BidiStreamingEchoRequest,
      O: BidiStreamingEchoResponse,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

