/* eslint-disable */
// @generated by protoc-gen-es v1.7.2 with parameter "ts_nocheck=false,target=ts"
// @generated from file greeter/v1/greeter.proto (package greeter.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message greeter.v1.SayHelloRequest
 */
export class SayHelloRequest extends Message<SayHelloRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  constructor(data?: PartialMessage<SayHelloRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "greeter.v1.SayHelloRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SayHelloRequest {
    return new SayHelloRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SayHelloRequest {
    return new SayHelloRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SayHelloRequest {
    return new SayHelloRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SayHelloRequest | PlainMessage<SayHelloRequest> | undefined, b: SayHelloRequest | PlainMessage<SayHelloRequest> | undefined): boolean {
    return proto3.util.equals(SayHelloRequest, a, b);
  }
}

/**
 * @generated from message greeter.v1.SayHelloResponse
 */
export class SayHelloResponse extends Message<SayHelloResponse> {
  /**
   * @generated from field: string message = 1;
   */
  message = "";

  constructor(data?: PartialMessage<SayHelloResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "greeter.v1.SayHelloResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SayHelloResponse {
    return new SayHelloResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SayHelloResponse {
    return new SayHelloResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SayHelloResponse {
    return new SayHelloResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SayHelloResponse | PlainMessage<SayHelloResponse> | undefined, b: SayHelloResponse | PlainMessage<SayHelloResponse> | undefined): boolean {
    return proto3.util.equals(SayHelloResponse, a, b);
  }
}

/**
 * @generated from message greeter.v1.StreamingEchoRequest
 */
export class StreamingEchoRequest extends Message<StreamingEchoRequest> {
  /**
   * @generated from field: string message = 1;
   */
  message = "";

  constructor(data?: PartialMessage<StreamingEchoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "greeter.v1.StreamingEchoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamingEchoRequest {
    return new StreamingEchoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamingEchoRequest {
    return new StreamingEchoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamingEchoRequest {
    return new StreamingEchoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StreamingEchoRequest | PlainMessage<StreamingEchoRequest> | undefined, b: StreamingEchoRequest | PlainMessage<StreamingEchoRequest> | undefined): boolean {
    return proto3.util.equals(StreamingEchoRequest, a, b);
  }
}

/**
 * @generated from message greeter.v1.StreamingEchoResponse
 */
export class StreamingEchoResponse extends Message<StreamingEchoResponse> {
  /**
   * @generated from field: string message = 1;
   */
  message = "";

  constructor(data?: PartialMessage<StreamingEchoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "greeter.v1.StreamingEchoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamingEchoResponse {
    return new StreamingEchoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamingEchoResponse {
    return new StreamingEchoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamingEchoResponse {
    return new StreamingEchoResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StreamingEchoResponse | PlainMessage<StreamingEchoResponse> | undefined, b: StreamingEchoResponse | PlainMessage<StreamingEchoResponse> | undefined): boolean {
    return proto3.util.equals(StreamingEchoResponse, a, b);
  }
}