/* eslint-disable */
// @generated by protoc-gen-connect-es v1.3.0 with parameter "ts_nocheck=false,target=ts"
// @generated from file greeter/v1/greeter.proto (package greeter.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SayHelloRequest, SayHelloResponse, StreamingEchoRequest, StreamingEchoResponse } from "./greeter_pb.js";
import { MethodKind, ServiceType } from "@bufbuild/protobuf";

/**
 * @generated from service greeter.v1.GreeterService
 */
export const GreeterService = {
  typeName: "greeter.v1.GreeterService",
  methods: {
    /**
     * @generated from rpc greeter.v1.GreeterService.SayHello
     */
    sayHello: {
      name: "SayHello",
      I: SayHelloRequest,
      O: SayHelloResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc greeter.v1.GreeterService.StreamingEcho
     */
    streamingEcho: {
      name: "StreamingEcho",
      I: StreamingEchoRequest,
      O: StreamingEchoResponse,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;